# Introduction to pandas

### some items are
* lis1
* lis2
* lis3

### To add link

[Sreeni's Linkedin](https://www.linkedin.com/in/sreenivasan-s-sreenivit/) is awesome

In [1]:
## To add Image

![](C:\Users\sreenis8\Pictures\Camera Roll\sreeni pic.jpg)

'[]' is not recognized as an internal or external command,
operable program or batch file.


In [2]:
2*3

6

In [3]:
import numpy as np

In [4]:
np.sin(90)   # give in radians

0.8939966636005579

In [5]:
%pwd

'C:\\Users\\sreenis8\\Downloads\\Linkedin Learning\\3. Python Numpy & pandas\\Ex_Files_Data_Science_Python\\Exercise Files\\Ch02\\02_01'

In [6]:
%%time
np.sin(1.57)

CPU times: total: 0 ns
Wall time: 0 ns


0.9999996829318346

In [7]:
import numpy as np

In [8]:
np.int64(2) ** 1000

0

#  ARRAYS in Numpy

In [9]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [10]:
type(arr)

numpy.ndarray

In [11]:
arr*arr

array([1, 4, 9])

In [12]:
arr+arr

array([2, 4, 6])

### multiplying two big arrays

In [13]:
v1 = np.random.rand(10000000)
v2 = np.random.rand(10000000)
v1*v2

array([0.03415384, 0.39072368, 0.00809613, ..., 0.14650919, 0.17315291,
       0.09416483])

In [14]:
%time
v1*v2

CPU times: total: 0 ns
Wall time: 0 ns


array([0.03415384, 0.39072368, 0.00809613, ..., 0.14650919, 0.17315291,
       0.09416483])

## To find dot product

In [15]:
arr = np.array([1,2,3])
np.dot(arr,arr)

14

## Other math operation

In [16]:
v = np.arange(12)

In [17]:
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
v.reshape((4,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
matrix = np.arange(12).reshape((4,3))
matrix

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
matrix.shape

(4, 3)

In [21]:
matrix2 = matrix.reshape((3,4))
matrix2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
matrix2[0,0]= 12
matrix2

array([[12,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Slicing in arrays

In [23]:
arr = [1,2,3,4,5]
arr[2:4]

[3, 4]

In [24]:
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [25]:
v[2:4]

array([3, 4])

In [26]:
arr

[1, 2, 3, 4, 5]

## Boolean operations on arrays

In [27]:
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr[ (arr>2) & (arr<8)]

array([3, 4, 5, 6, 7])

In [29]:
 arr[ (arr<2) | (arr>7)]

array([0, 1, 8, 9])

# 1st march


In [30]:
%pwd

'C:\\Users\\sreenis8\\Downloads\\Linkedin Learning\\3. Python Numpy & pandas\\Ex_Files_Data_Science_Python\\Exercise Files\\Ch02\\02_01'

In [31]:
import geo

In [32]:
import sys
sys.path

['C:\\Users\\sreenis8\\Downloads\\Linkedin Learning\\3. Python Numpy & pandas\\Ex_Files_Data_Science_Python\\Exercise Files\\Ch02\\02_01',
 'C:\\Softwares\\python311.zip',
 'C:\\Softwares\\DLLs',
 'C:\\Softwares\\Lib',
 'C:\\Softwares',
 '',
 'C:\\Softwares\\Lib\\site-packages',
 'C:\\Softwares\\Lib\\site-packages\\win32',
 'C:\\Softwares\\Lib\\site-packages\\win32\\lib',
 'C:\\Softwares\\Lib\\site-packages\\Pythonwin']

#### To view the code type ??geo

In [33]:
??geo 

Type:        module
String form: <module 'geo' from 'C:\\Users\\sreenis8\\Downloads\\Linkedin Learning\\3. Python Numpy & pandas\\Ex_Files_Data_Science_Python\\Exercise Files\\Ch02\\02_01\\geo.py'>
File:        c:\users\sreenis8\downloads\linkedin learning\3. python numpy & pandas\ex_files_data_science_python\exercise files\ch02\02_01\geo.py
Source:     
"""Distance on a circle"""

import numpy as np


def circle_dist(lat1, lng1, lat2, lng2):
    """
    Distance on a circle (in km)

    Parameters
    ----------
    lat1, lng1, lat2, lng2: float or array of float

    Returns
    -------
    distance:
      distance from ``(lat1, lng1)`` to ``(lat2, lng2)`` in kilometers.
    """
    phi1 = np.deg2rad(90 - lat1)
    phi2 = np.deg2rad(90 - lat2)

    theta1 = np.deg2rad(lng1)
    theta2 = np.deg2rad(lng2)

    cos = (np.sin(phi1) * np.sin(phi2) * np.cos(theta1 - theta2) +
           np.cos(phi1) * np.cos(phi2))
    arc = np.arccos(cos)
    return arc * 6373  # Earth radius in km

In [34]:
from geo import circle_dist

In [35]:
lat1, lng1 = df.iloc[0].lat, df.iloc[0].lng
lat2, lng2 = df.iloc[1].lat, df.iloc[1].lng

NameError: name 'df' is not defined

In [1]:
import pandas as pd
import numpy as np
s = pd.Series(np.arange(5))
s

0    0
1    1
2    2
3    3
4    4
dtype: int32

In [3]:
s.shift()  #will shift downwards

0    NaN
1    0.0
2    1.0
3    2.0
4    3.0
dtype: float64

In [6]:
s.shift(-1)  #will shift upwards

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
dtype: float64

# 5.Conda

In [1]:
import folium

ModuleNotFoundError: No module named 'folium'

In [3]:
import pymongo